### ISSUE TITLE
Can't install - Error: Could not find the .cmi file for interface tools/rqueue.mli.

### ISSUE THREAD

**Issue by svandragt** [drfill/homebrew-liquidsoap#24] opened 2015-08-01 10:52 UTC
patching file src/tools/http.ml
patching file src/tools/tutils.ml
patching file src/tools/utils.ml
patching file src/tools/wav.ml
==> ./configure --prefix=/usr/local/Cellar/liquidsoap/1.1.1 --with-user=me
==> make
File "tools/rqueue.ml", line 1:
Error: Could not find the .cmi file for interface tools/rqueue.mli.
make[2]: *** [tools/rqueue.cmx] Error 2
make[1]: *** [all-auto-ocaml-prog] Error 2
make: *** [all-subdirs] Error 2
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'

env | sort | grep pkg

    PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10

**Comment by jphastings** [comment] 2015-08-08 07:51
This looks duplicate of #23, I'm having the same issue.

**Comment by shimmyshack** [comment] 2015-08-19 03:16
see update to [#23](https://github.com/drfill/homebrew-liquidsoap/issues/23) in case it is of use

**Closed** 2015-08-19 14:13 UTC
